import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import type { BlockSchemaMap } from './normalizer'
import { normalizeBlockSchema } from './normalizer'

interface Fixture {
  name: string
  input: BlockSchemaMap
  expected: BlockSchemaMap
  field_order: string[]
}

const fixtures: Fixture[] = JSON.parse(
  readFileSync(join(__dirname, '__fixtures__', 'schema-normalization-pipeline.json'), 'utf8')
)

describe('normalizeBlockSchema', () => {
  // Fixtures are generated by the CMS repo's SchemaNormalizationPipelineTest —
  // the PHP implementation is the source of truth for both suites.
  it.each(fixtures)('matches the CMS pipeline for $name', ({ input, expected, field_order }) => {
    const result = normalizeBlockSchema(input)

    expect(Object.keys(result)).toEqual(field_order)
    expect(result).toEqual(expected)
  })

  it.each(fixtures)('is idempotent for $name', ({ expected }) => {
    expect(normalizeBlockSchema(expected)).toEqual(expected)
  })
})
